### PR TITLE
Added git/workflow.md

### PR DESCRIPTION
**Pull request by Ashrjz**
[Preview](https://ashishraj-0.github.io/notes/git/workflow/)

### CODE REVIEW

**Comment by ab-emptycup** [comment]
Hi Ashish,

This note is much more clear. Nice work. Here's some suggestions for improvements:

- Your note gives instructions to setup the repo to connect to the HTTP endpoint instead of the SSH endpoint. There are a couple of drawbacks to this. First is that you have to type in the password every time you push to the repo. The second is that you cannot script git access because of the password prompt. For example, if you are setting up a remote server, you may create a bash script that installs all the necessary dependencies, fetches the code from github and then runs the server. You can run this script on any machine and it will make sure your server is started on that machine. With HTTP access, you can't do this because that script would stop and ask for your password. The benefit of setting up SSH access is that, your script can directly use the SSH key file and doesn't have to pause execution. I hope that makes sense.
- You can link this note from the overview note: basics/overview.md. I think this makes more sense after an intro to signing up on Github. So, you can move the "workflow" as 2nd point after "Github" under Basics/Overview/Git. If you are interested, you can write the note on setting up SSH access to Github also. It's okay even if you don't.
- Minor polish: Change the subheading to "Keeping your fork updated" to avoid the long subheading in the Table of Contents.
- Minor polish: Add another subheading "References" at the end before the "Github flow" link. More links can be added there if necessary. Also, whenever possible, instead of just "Github workflow", add a descriptive sentence to explain what info can be found on the link. For ex: this case it can be: "Workflow recommended by Github"

**Comment by Ashrjz** [comment]
Updated notes as per your suggestions. [Preview](https://ashishraj-0.github.io/notes/)

**Comment by ab-emptycup** [comment]
Cool. It looks clean now. Can you squash your changes into a single commit with a log message mentioning the different changes. That way when I merge, the entire change will appear in a single commit. Generally, the useful benefit of squashing commits is that all the changes pertaining to a logical addition will be visible in one commit. So, it becomes easy looking back to understand why some change was made. Also, it lets you avoid broken / incomplete states being part of the commit history.

You can squash your commit history by using `git rebase`. In particular, checkout `git rebase -i`.

**Comment by ab-emptycup** [comment]
PS: One very very trivial change. Can you remove the full stop after the links in the references section? Sorry again for being pedantic. Just want to maintain good hygiene for the content. Thanks.

**Comment by Ashrjz** [comment]
I did all the changes as per your requirements. [Preview](https://ashishraj-0.github.io/notes/git/workflow/#references)

**Comment by ab-emptycup** [comment]
Merged! It turns out that Github has this option to automatically squash the commits in a pull request before merging. I didn't know that. I guess, that's learning for me.

This is good work, Ashish. A lot of improvement compared to the first pull request. Hope you're learning something new.

**Pull request merged**
