### PR TITLE
Added mkdocs.md & markdown.md

### PR DESCRIPTION
**Pull request by Ashrjz**

### CODE REVIEW

**Comment by ab-emptycup** [comment]
Good work, Ashish! Props for adding the note on Markdown as well.

We can work on improvements to the pull request by continuing the conversation here. You can make more commits and push to the same branch and they will keep updating the pull request. 

I do have a few suggestions for improvements, but before we do that, I want to see how the site looks once this pull request is merged. That means I need to see your deployment. But since your development deployment is in your local machine. I can't access it. You need to deploy your development version publicly, so that I can access it. Luckily, GitHub itself offers a way to publish static websites through GitHub pages.

Even better is the fact that mkdocs itself has a feature to deploy directly to Github. If you type `mkdocs` on your terminal, it shows command line options available. One of them is `mkdocs gh-deploy` which deploys your branch to a Github pages endpoint on your github account. You can google for "Github Pages" for more info on how this works.

So, the next step for you is to try that out and share a live preview link. You can comment on this thread itself if you run into any problems. I'll find some time and help you set this up.

**Comment by Ashrjz** [comment]
`https://ashishraj-0.github.io/notes/`
Here's the link for the preview of the site.
Let me know of the changes to be made.

**Comment by ab-emptycup** [comment]
Yeah, I can check the preview now. Thanks.

A few suggestions for improving the notes:

- Link the notes from the Others section on the /basics page also, at the bottom.
- Use h2 / ## for subheadings in markdown.md. Blockquotes are usually reserved for quotes from external sources/people. Even if it looks okay today, the material-for-mkdocs theme may change tomorrow and style block quotes differently. Or a plugin might parse the markdown and build a table of contents using subheadings and miss these blockquote subheadings. So, a general rule is "Don't break semantics".
- It is better to avoid linking to external sources as much as possible. This is because the external page/article/video might be taken down or maybe changed tomorrow or may become outdated in some cases. It is recommended to link to original documentation whenever possible. Blog's or tech articles or news might just take down their website or change the link or fill them with ads or change the content or the page layout.
- When adding an external resource, it is recommended to summarize the crucial info from the page in 2-3 sentences and then add it as "Learn more" link or add it as a reference as the end of the note. This enables the reader to get what they want without navigating and searching in more pages. Ideally, a user should just get everything they need on the note itself, without following other links. But useful reference links can be added at the end of the note.
- Always approach the note from the direction of "What does someone starting need to know to get their work done?". In this case for example: What is markdown and what is it used for... approaches from the technology perspective, not the user's perspective. The user's perspective is "Instead of writing HTML, you can write in markdown which is human readable." Then "mkdocs converts markdown to HTML during the build step". Then "How can I write the common elements I need in Markdown". Similarly with mkdocs as well: "How to set it up?" then "How to add a note?" then "How to test / preview the note" then "How to publish?" and then "How to change some configuration?"
- Avoid subheadings unless there are at least 3 large bullet points under it. This simplifies the note and makes it easy to read. Also, keep the subheading text simple and short as they will be added in Table of Contents on the right. It is better to simply have more bullet points as the users are expected to go through the entire note and not just skip directly to subheadings. 
- Skip the ":" after the main page title. Sorry if that's too pedantic. I have learned that paying attention to these small details makes a big difference in the long term, not just to the product but also to the company culture. Hope you understand.

That's all that I can think of now. Looking forward to merging your pull request. This is the first pull request on this repo. Kudos, this is a good start! You can make changes and push again.

PS: You should also mention what change you are making in your commit message, so that when you look at the log, you know what you modified instead of just filenames. That's a general rule, but these are trivial changes and all these are good. Keep going.

**Comment by ab-emptycup** [comment]
I think I should add those points to `/guidelines`. I'll add an issue to track these things.

**Comment by ab-emptycup** [comment]
Please share the updated public preview link when you are satisfied with the changes. I'll take a look and add any polishes and merge if it is good to go.

**Comment by Ashrjz** [comment]
[Preview Link](https://ashishraj-0.github.io/notes/)
Do let me know, if the documentation needs something else.

**Comment by ab-emptycup** [comment]
I merged the PR after making some changes & polishes. Just one call out from your note:

You noted to create the virutalenv after installing `mkdocs`. Then `mkdocs` would be installed in the global path. What virtualenv does is it creates a virtual environment just for the project, so that you don't pollute the global enviroment with every project's dependencies. That means, you have to create a virtualenv first, then activate it and install dependencies like `mkdocs`, so that they are accessible only within that project.

Other than that point, everything else was just formatting polishes. I also noted, the changes you made in the last few commits which improved readability a lot. Hopefully, my polishes do the same. Do spend some time on the note if you can.

**Comment by ab-emptycup** [comment]
I also wanted to explain about the merge:

I fetched your branch. Added my polishes. Then I squashed all commits in this pull request into a single commit and merged it into my "main" branch. Since, the commits have been squashed into a single new commit, the PR says there is a conflict. Does that make sense?

Now you'll have to reset your main branch to my main branch again. Let me know how that goes. Feel free to ask if you have any doubts. If you're clear and get your 'main' branch synced with my 'main', we'll close this PR and go to the next step.

**Pull request closed without merging**
